# Generated by Django 4.2.3 on 2023-07-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='category',
            field=models.CharField(choices=[('STD', 'Standard'), ('LTN', 'Latin')], default='STD', max_length=8),
        ),
        migrations.AlterField(
            model_name='style',
            name='rating',
            field=models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='5', max_length=5),
        ),
    ]
