# Generated by Django 4.2.3 on 2023-07-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0003_style_description_alter_style_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.ImageField(default='static/images/dance.png', height_field=300, upload_to='static/images/', width_field=300),
        ),
    ]
