# Generated by Django 4.2.3 on 2023-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0004_style_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='height',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='style',
            name='width',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.ImageField(default='static/images/dance.png', height_field='height', upload_to='static/images/', width_field='width'),
        ),
    ]
